(function (root, factory) {
  if (typeof module === "object" && module.exports) module.exports = factory();
  else root.StarshipCoreKits = factory();
}(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";
  return Object.freeze({
    celesia: { rarity: 4, role: "指揮", secondaryRole: "協同輸出", maxHp: 1320, attack: 188, defense: 160, speed: 112, range: 2, attackName: "星式協作斬", skillName: "星痕指令", skillPower: 1.4, skillEffect: "以攻擊力 140% 傷害標記敵人，使其受傷增加 8%，標記持續 2 輪；不同隊友命中時，自己每輪追擊 1 次，倍率 45%。", signature: { type: "core", kind: "star", cooldown: 3 }, constellations: ["C1 星痕及受傷增加 8% 的效果由 2 輪延為 3 輪。", "C2 同一輪第二位不同隊友命中星痕目標時，該次實際傷害額外增加 15%。", "C3 星痕指令傷害由攻擊力 140% 提至 170%；每輪自身追擊由 45% 提至 55%。", "C4 星痕目標被擊倒時，轉標至當時生命值最高的存活敵人 2 輪，並使自身技能冷卻減少 1。", "C5 星痕目標受傷增加由 8% 提至 12%；每輪自身追擊由 55% 提至 65%。", "C6 第三位不同隊友命中同一星痕目標時，每輪額外發動 1 次自身攻擊力 90% 的追擊，並使技能冷卻減少 1；每個目標每輪最多觸發 1 次。"] },
    reyn: { rarity: 3, role: "守衛", secondaryRole: "護衛", maxHp: 1200, attack: 148, defense: 178, speed: 119, range: 1, attackName: "巡林短弓", skillName: "巡林掩護", skillPower: 1, skillEffect: "保護生命比例最低的其他隊友 2 輪，將其受傷的 40% 轉為自己承擔；自己實際承受轉移量的 75%。", signature: { type: "core", kind: "cover", cooldown: 3 }, constellations: ["C1 施放掩護時，被保護者速度提高 8%，持續 2 輪。", "C2 掩護分擔傷害後，每輪首次對首名存活敵人反擊，傷害為自身攻擊力 70%。", "C3 自己承受的轉移傷害由分擔量的 75% 降至 68%；被保護者仍轉出原傷害的 40%。", "C4 施放時若被保護者生命低於 40%，附加雷恩最大生命 8% 的護盾；單人護盾總量上限為受盾者最大生命 28%。", "C5 反擊倍率由 70% 提至 90%，並使反擊目標攻擊力降低 10%，持續 2 輪。", "C6 掩護中的隊友將受致命傷時，改為轉移該次傷害的 100%；自己只承受轉移量的 50%，最低保留 1 點生命，觸發後移除這次掩護。"] },
    lia: { rarity: 3, role: "治療", secondaryRole: "防護", maxHp: 1100, attack: 112, defense: 152, speed: 110, range: 2, attackName: "星光藥針", skillName: "回覆援護", skillPower: 1, skillEffect: "治療生命比例最低的受傷隊友，立即回復莉亞最大生命的 18%，並給予每輪 6% 的持續治療，共 2 輪。", signature: { type: "core", kind: "lia", cooldown: 3 }, constellations: ["C1 每輪回復莉亞最大生命 6% 的持續治療由 2 輪延為 3 輪。", "C2 即時治療溢出時，將溢出量的 50% 轉成護盾，上限為莉亞最大生命的 10%；受盾者護盾總上限為自身最大生命 28%。", "C3 即時治療量由莉亞最大生命 18% 提至 22%。", "C4 技能治療後若目標生命仍低於 40%，移除其可淨化負面效果，並使莉亞速度提高 10%，持續 1 輪。", "C5 每輪持續治療量由莉亞最大生命 6% 提至 8%，持續 3 輪。", "C6 每名隊友每場首次降至 30% 生命以下且仍存活時，立即回復莉亞最大生命 10%，並獲得每輪回復 8% 的效果 1 輪。"] },
    isar: { rarity: 3, role: "獵人", secondaryRole: "前排", maxHp: 1260, attack: 175, defense: 160, speed: 88, range: 1, attackName: "獵線重擊", skillName: "大型獵擊", skillPower: 1.65, skillEffect: "造成自身攻擊力 165% 的傷害；命中前目標生命高於 50% 時再乘 1.2。使用後自身受傷減少 15%，持續 1 輪。", signature: { type: "core", kind: "hunt", cooldown: 3 }, constellations: ["C1 對生命高於 50% 的目標，額外倍率由 1.2 提至 1.25；施放後自身受傷減少由 15% 提至 20%，持續 1 輪。", "C2 施放獵擊後至下一輪，受擊時每輪首次對首名存活敵人反擊，傷害為自身攻擊力 80%。", "C3 獵擊基礎倍率由自身攻擊力 165% 提至 195%；對高生命目標仍乘 C1 的 1.25。", "C4 自身生命低於 50% 時受擊傷害再降低 15%；受擊後若仍存活且低於 50%，防禦提高 15%、受療提高 10%，持續 2 輪。", "C5 反擊倍率由 80% 提至 110%，並使反擊目標攻擊力降低 10%，持續 2 輪。", "C6 其他生命低於 50% 的隊友受擊時，每隔至少 2 輪替其承受該次剩餘傷害的 30%，自己最低保留 1 點生命，並對首名敵人追擊自身攻擊力 80%。"] },
    chodan: { rarity: 4, role: "節奏", secondaryRole: "輔助", maxHp: 1260, attack: 160, defense: 160, speed: 122, range: 2, attackName: "月式鼓擊", skillName: "月式鼓點", skillPower: 1, skillEffect: "全隊速度提高 10% 共 2 輪；接下來 2 輪內，其他隊友的前 2 次技能傷害、治療或護盾提高 10%。", signature: { type: "core", kind: "beat", cooldown: 3 }, constellations: ["C1 合拍可強化的其他隊友技能次數由 2 次增加為 3 次；須在施放後 2 輪內使用。", "C2 合拍技能若治療或提供護盾，接受者受傷減少 8%，持續 2 輪。", "C3 月式鼓點的全隊速度增幅由 10% 提至 11%，持續 2 輪。", "C4 每場戰鬥首次有其他隊友使用合拍技能時，Chodan 的技能冷卻減少 1。", "C5 合拍技能的傷害、治療或護盾增幅由 10% 提至 14%。", "C6 同一次鼓點期間，3 位不同隊友各使用技能參與合拍後，追加 1 次合拍，並使全隊速度提高 5% 共 2 輪；每次鼓點最多觸發一次。"] },
    magenta: { rarity: 4, role: "爆發", secondaryRole: "削弱", maxHp: 1160, attack: 228, defense: 130, speed: 105, range: 2, attackName: "低音震波", skillName: "旅行低音", skillPower: 1.75, skillEffect: "主目標受自身攻擊力 175% 傷害，其餘敵人受 110%；若主目標已有負面效果，主目標傷害再乘 1.2。主目標防禦降低 12% 共 2 輪。", signature: { type: "core", kind: "bass", cooldown: 3 }, constellations: ["C1 主目標防禦降低幅度由 12% 提至 15%，持續 2 輪。", "C2 若施放前主目標已有負面效果，其餘敵人的技能傷害各追加等同自身攻擊力 35% 的原始傷害。", "C3 主目標基礎倍率由攻擊力 175% 提至 210%，其餘敵人由 110% 提至 125%。", "C4 帶低音標記的目標被擊倒時，將標記轉給當時生命最高的存活敵人 2 輪，並使新目標防禦降低 15% 共 2 輪。", "C5 主目標在施放前已有負面效果時的額外傷害倍率由 1.2 提至 1.3。", "C6 隊友命中低音標記目標後，Magenta 每輪首次追擊自身攻擊力 70%，並將該標記期限延長 1 輪。"] },
    hina: { rarity: 4, role: "射手", secondaryRole: "標記", maxHp: 1100, attack: 220, defense: 124, speed: 128, range: 3, attackName: "弦音箭", skillName: "弦音標記", skillPower: 1.5, skillEffect: "造成自身攻擊力 150% 傷害，標記目標 2 輪並使其受傷增加 8%。", signature: { type: "core", kind: "string", cooldown: 2 }, constellations: ["C1 標記與受傷增加 8% 的效果由 2 輪延為 3 輪；施放時自身速度提高 5% 共 1 輪。", "C2 其他隊友命中標記目標後，Hina 每輪首次追擊自身攻擊力 45%。", "C3 弦音標記的直接傷害倍率由自身攻擊力 150% 提至 180%。", "C4 標記目標速度降低 10% 共 2 輪；該目標被擊倒時，標記轉移至當時生命最高的存活敵人 2 輪。", "C5 每輪追擊倍率由自身攻擊力 45% 提至 65%。", "C6 標記目標被擊倒並轉標後，立即對新目標追擊自身攻擊力 80%；轉標仍以 C4 為前提。"] },
    siyeon: { rarity: 4, role: "拾音", secondaryRole: "延遲治療", maxHp: 1240, attack: 148, defense: 160, speed: 116, range: 2, attackName: "回音脈衝", skillName: "回音採集", skillPower: 1, skillEffect: "立即治療生命比例最低的 2 名隊友，各回復 Siyeon 最大生命 8%；記錄之後受傷的 30%，第 2 輪結算回復，上限為 Siyeon 最大生命 14%。", signature: { type: "core", kind: "echo", cooldown: 3 }, constellations: ["C1 延遲回復上限由 Siyeon 最大生命 14% 提至 18%；記錄與結算仍相隔 2 輪。", "C2 回音記錄的傷害超出延遲回復上限時，超出量的 50% 轉為護盾，上限為 Siyeon 最大生命 8%；受盾者護盾總上限為自身最大生命 28%。", "C3 施放時對 2 名目標的立即治療由 Siyeon 最大生命 8% 提至 11%。", "C4 回音結算時，移除目標在記錄期間獲得的 1 個可淨化負面效果。", "C5 記錄受傷比例由 30% 提至 40%，延遲回復上限由 Siyeon 最大生命 18% 提至 20%。", "C6 每次回音採集最多為 1 名目標提前結算：任一記錄中的隊友生命低於 25% 且仍存活時，提前回復已記錄量，上限為 Siyeon 最大生命 20%；另一名目標仍按原時間結算，提前結算者減傷 10% 至原定結算輪。"] }
  });
}));
